### ISSUE TITLE
Literal "(" in a `=for Pod::Coverage` section -> Obtuse error.

### ISSUE THREAD

**Issue by kentfredric** [rjbs/Pod-Coverage-TrustPod#1]
Usecase: 

I accidentally forgot an `=end` somewhere when I had a `=begin Pod::Coverage`, and I spent a while tracking down the cryptic 

```
# Unmatched ( in regex; marked by <-- HERE in m/\A( <-- HERE \z/ at /home/kent/perl5/perlbrew/perls/5.22.1-nossp-sdbm-nopmc/lib/site_perl/5.22.1/Pod/Coverage/TrustPod.pm line 60.
```

In my POD test.

I'm not sure if Regex are intentionally supported here, but its both undocumented and the error handling is a bit poor.

Here's the most reduced case I could make from a pure Pod::Coverage test ( getting closer than this seems difficult for now )

[pod_coverage_bomb.t.txt](https://github.com/rjbs/Pod-Coverage-TrustPod/files/244428/pod_coverage_bomb.t.txt)

``` perl
# vim: syntax=perl
use strict;
use warnings;

use Test::More;
use Test::TempDir::Tiny qw( in_tempdir );
use Path::Tiny qw( path );
use Test::Pod::Coverage 1.08;
use Pod::Coverage::TrustPod;

# ABSTRACT: Test Pod::Coverage fuckups

my $bad_regex = <<'EOF';
package Example;


sub dummy {}

1;

__END__
=pod

=for Pod::Coverage (

EOF

in_tempdir "bad_regex" => sub {
    my $cwd = shift;
    local @INC = ( $cwd . '/lib', @INC );
    path('lib')->mkpath;
    path('lib/Example.pm')->spew_raw($bad_regex);

    local $@;
    ok(
        eval {
            all_pod_coverage_ok(
                { coverage_class => 'Pod::Coverage::TrustPod' } );
            1;
        },
        "didn't bail"
    ) or diag explain $@;
};

done_testing;
```

However, Its possible that regex was intended and useful, as this example case demonstrates a use for:

[pod_coverage_useful.t.txt](https://github.com/rjbs/Pod-Coverage-TrustPod/files/244432/pod_coverage_useful.t.txt)

``` perl

# vim: syntax=perl
use strict;
use warnings;

use Test::More;
use Test::TempDir::Tiny qw( in_tempdir );
use Path::Tiny qw( path );
use Test::Pod::Coverage 1.08;
use Pod::Coverage::TrustPod;

# ABSTRACT: Test Pod::Coverage fuckups

my $bad_regex = <<'EOF';
package Example;

sub fun_suffix {}
sub otherfun_suffix {}

1;

__END__
=pod

=for Pod::Coverage .*_suffix

EOF

in_tempdir "useful_regex" => sub {
    my $cwd = shift;
    local @INC = ( $cwd . '/lib', @INC );
    path('lib')->mkpath;
    path('lib/Example.pm')->spew_raw($bad_regex);

    local $@;
    all_pod_coverage_ok(
      { coverage_class => 'Pod::Coverage::TrustPod' }
    );
};

done_testing;
```

**Comment by rjbs** [comment]
Since version 0.000 in 2008, the docs say:

> This file would report full coverage, because any non-empty lines inside a block of POD targeted to Pod::Coverage are treated as trustme patterns. Leading and trailing whitespace is stripped and the remainder is treated as a regular expression.

That said, I have added a better error message in the latest release.
